# Generated by Django 5.1 on 2024-10-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
    ]
