# Generated by Django 5.1 on 2024-10-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField()),
                ('occupies_chef', models.BooleanField(default=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='recipe_optimizer.recipestep')),
            ],
        ),
    ]
