# Generated by Django 5.1 on 2024-10-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_optimizer', '0002_recipestep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
